'use client';

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { fetchWithAuth } from '@/lib/api';
import { Brain, Sparkles, TrendingUp, ShieldAlert, Zap, Target, BookOpen } from 'lucide-react';
import { cn } from '@/lib/utils';

export default function BiasProfilePage() {
  const { user } = useAuth();
  const [profile, setProfile] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const loadProfile = async () => {
      try {
        const data = await fetchWithAuth('/analysis/profile-summary');
        setProfile(data.analysis);
      } catch (err: any) {
        setError('Failed to generate your cognitive profile.');
      } finally {
        setLoading(false);
      }
    };
    loadProfile();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex flex-col items-center justify-center p-10 text-center space-y-6">
        <div className="relative">
          <div className="w-20 h-20 border-2 border-gold/20 rounded-full animate-ping absolute opacity-40" />
          <Brain size={48} className="text-gold animate-pulse relative" />
        </div>
        <div>
          <h2 className="text-2xl font-serif text-foreground">Synthesizing Your Cognitive DNA</h2>
          <p className="text-muted-foreground mt-2 max-w-sm mx-auto font-medium italic">Grok-3 is auditing your entire decision history to identify overarching patterns.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white font-sans text-foreground">
      <div className="max-w-5xl mx-auto p-10 pb-24">
        <header className="mb-16 space-y-4">
          <div className="flex items-center gap-2 text-gold">
            <Sparkles size={16} />
            <span className="text-[10px] uppercase tracking-[0.3em] font-bold">Analysis Aggregate</span>
          </div>
          <h1 className="text-5xl font-serif text-foreground tracking-tight">Your Bias Profile</h1>
          <p className="text-xl text-muted-foreground max-w-2xl leading-relaxed italic font-medium">
            A high-fidelity mirror of your decision-making architecture, based on every entry in your ledger.
          </p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 mb-12">
          {/* Pulse Stats */}
          <div className="lg:col-span-1 space-y-6">
            <Card className="bg-bg-2 border-border/50 overflow-hidden relative group shadow-sm">
              <div className="absolute top-0 right-0 w-24 h-24 bg-gold/5 blur-3xl -mr-12 -mt-12 group-hover:bg-gold/10 transition-colors" />
              <CardHeader className="pb-2">
                <CardDescription className="text-[10px] uppercase tracking-widest text-gold font-bold">Calibration</CardDescription>
                <CardTitle className="text-3xl font-serif text-foreground">Elite</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs text-muted-foreground font-medium">Your reasoning accuracy is in the top 15% of recorded analysts.</p>
              </CardContent>
            </Card>

            <Card className="bg-bg-2 border-border/50 overflow-hidden relative group shadow-sm">
              <div className="absolute top-0 right-0 w-24 h-24 bg-teal/5 blur-3xl -mr-12 -mt-12 group-hover:bg-teal/10 transition-colors" />
              <CardHeader className="pb-2">
                <CardDescription className="text-[10px] uppercase tracking-widest text-teal font-bold">Awareness</CardDescription>
                <CardTitle className="text-3xl font-serif text-foreground">High</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-xs text-muted-foreground font-medium">Successfully identified 4 major biases in the last 30 days.</p>
              </CardContent>
            </Card>
          </div>

          {/* Main AI Report */}
          <div className="lg:col-span-3">
            <Card className="bg-white border-border/60 relative shadow-[0_20px_50px_rgba(0,0,0,0.03)] overflow-hidden min-h-[600px] rounded-3xl">
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_-20%,rgba(212,175,55,0.05),transparent)] pointer-events-none" />
              <CardHeader className="border-b border-border/50 pb-6 flex flex-row items-center justify-between bg-bg-2/50">
                <div>
                  <CardTitle className="text-2xl font-serif text-foreground">Cognitive DNA Report</CardTitle>
                  <CardDescription className="font-medium italic">Generated by Grok-3 Intelligence Layer</CardDescription>
                </div>
                <div className="w-12 h-12 bg-gold/10 rounded-2xl flex items-center justify-center text-gold">
                    <Brain size={28} />
                </div>
              </CardHeader>
              <CardContent className="pt-10 px-10">
                <div className="whitespace-pre-wrap text-foreground font-medium leading-relaxed prose prose-sm prose-gold max-w-none">
                  {profile}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Strategies Section */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-8 bg-bg-2 border border-border/50 rounded-3xl space-y-4 hover:border-gold/30 transition-all shadow-sm group">
            <ShieldAlert size={28} className="text-gold group-hover:scale-110 transition-transform" />
            <h4 className="text-xl font-serif text-foreground">Defense Strategy</h4>
            <p className="text-sm text-muted-foreground leading-relaxed font-medium">Prioritize Pre-Mortems on career decisions to neutralize your detected Optimism Bias.</p>
          </div>
          <div className="p-8 bg-bg-2 border border-border/50 rounded-3xl space-y-4 hover:border-gold/30 transition-all shadow-sm group">
            <Zap size={28} className="text-gold group-hover:scale-110 transition-transform" />
            <h4 className="text-xl font-serif text-foreground">Growth Lever</h4>
            <p className="text-sm text-muted-foreground leading-relaxed font-medium">Your financial calibration is excellent. Trust your higher-confidence ranges in this domain.</p>
          </div>
          <div className="p-8 bg-bg-2 border border-border/50 rounded-3xl space-y-4 hover:border-gold/30 transition-all shadow-sm group">
            <Target size={28} className="text-gold group-hover:scale-110 transition-transform" />
            <h4 className="text-xl font-serif text-foreground">Core Focus</h4>
            <p className="text-sm text-muted-foreground leading-relaxed font-medium">Reducing the "Hindsight Gap" in relationship entries by logging more immediate internal states.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
